app1/urls.py
from django.urls import path
from .views import *

app_name = "app1"

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('registrar/', RegistroUsuario.as_view(), name='registro'),
    path('reviews/<int:id>', ComentarioView.as_view(), name='comentar'),
    path('hotel/<int:pk>', DetalleHotel.as_view(), name='detalle_hotel'),
]

hotel_advisor/urls.py
from django.contrib import admin
from django.urls import path, include
from data_script import fake_data


print("Cargando Datos")
#fake_data.crear()


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

app1/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Hoteles(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=500, blank=True, null=True)
    calificacion = models.DecimalField(
        max_digits=11,
        decimal_places=2,
        null=True)
    cant_votos = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.nombre


class Comentarios(models.Model):
    hotel = models.ForeignKey(Hoteles, on_delete=models.CASCADE)
    nombre_usuario = models.CharField(max_length=50)
    comentario = models.CharField(max_length=500)
    fecha = models.DateField(blank=True, null=True)
    puntuacion = models.IntegerField(blank=True, null=True)


class Atributos(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre


class AtributosHotel(models.Model):
    hotel = models.ForeignKey(Hoteles, on_delete=models.CASCADE)
    atributo = models.ForeignKey(Atributos, on_delete=models.CASCADE)
    valor_atributo = models.CharField(max_length=500)

app1/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Comentarios


class FormularioRegistro(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email','password1','password2')

    def __init__(self, *args, **kwargs):
        super(FormularioRegistro, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'

class ComentarioForm(forms.ModelForm):
    CHOICES = ((1, 1),(2, 2),(3, 3),(4, 4),(5, 5))
    calificacion = forms.ChoiceField(choices=CHOICES)

    class Meta:
        model = Comentarios
        widgets = {
            'comentario': forms.Textarea(attrs={'class': 'form-control'}),
            'calificacion': forms.Select(attrs={'class': 'form-control'}),
        }
        fields = ['calificacion','comentario']

app1/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import View
from django.views.generic.edit import UpdateView, CreateView
from django.views.generic import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db.models import Sum
from .models import Comentarios, Hoteles, AtributosHotel
from .forms import FormularioRegistro, ComentarioForm

import datetime


# Create your views here.
class IndexView(View):
    template_name = 'app1/index.html'

    def get(self, request):
        context = {}

        context['hoteles'] = Hoteles.objects.all().order_by('-cant_votos')
        context['comentarios'] = Comentarios.objects\
                                    .all().order_by('-fecha')[:5]

        return render(request, self.template_name, context)
    
    def post(self, request):
        estrellas = self.request.POST.get('estrellas')
        buscar = self.request.POST.get('search')
        cant_votos= self.request.POST.get('cant_votos')
        calificacion = self.request.POST.get('calificacion')
        nombre = self.request.POST.get('nombre')

        context = {}
        if estrellas is not None:
            print(estrellas)
            context['hoteles'] = Hoteles.objects.filter(calificacion__lte=int(estrellas)+0.999, calificacion__gte=estrellas)
        

        if buscar is not None:
            context['hoteles'] = Hoteles.objects.filter(nombre__icontains=buscar)
        

        if cant_votos is not None:
            context['hoteles'] = Hoteles.objects.all().order_by('-cant_votos')
        
        
        if nombre is not None:
            print("Sucediendo")
            context['hoteles'] = Hoteles.objects.all().order_by('nombre')
        
        
        if calificacion is not None:
            context['hoteles'] = Hoteles.objects.all().order_by('-calificacion')
        


        
        context['comentarios'] = Comentarios.objects\
                                   .all().order_by('-fecha')[:5]

        return render(request, self.template_name, context)


class RegistroUsuario(CreateView):
    model = User
    template_name = 'app1/registro.html'
    form_class = FormularioRegistro
    success_url = reverse_lazy('app1:index')


class DetalleHotel(DetailView):
    model = Hoteles
    context_object_name = 'detalle_hotel'
    template_name = 'app1/detalle_hotel.html'

    def get_context_data(self, **kwargs):
        context = super(DetalleHotel, self).get_context_data(**kwargs)
        hotel = self.get_object()
        context['atributos_hotel'] = AtributosHotel.objects.filter(hotel=hotel)
        comentarios = Comentarios.objects.filter(hotel=hotel)
        context['comentarios'] = comentarios
        return context 


class ComentarioView(LoginRequiredMixin, CreateView):
    model = Comentarios
    template_name = 'app1/comentar.html'
    form_class = ComentarioForm

    def get_context_data(self, **kwargs):
        context = super(ComentarioView, self).get_context_data(**kwargs)
        context['hotel'] = Hoteles.objects.get(id=self.kwargs['id'])
        print(context['hotel'])
        return context 
    
    def form_valid(self, form):
        data_input = form.cleaned_data
        print(data_input['calificacion'])
        user = self.request.user
        hotel = Hoteles.objects.get(id=self.kwargs['id'])
        form.instance.hotel = hotel
        form.instance.puntuacion = int(data_input['calificacion'])
        form.instance.nombre_usuario = user.username
        form.instance.fecha = datetime.datetime.now()
        return super().form_valid(form)

    def get_success_url(self):
        hotel = Hoteles.objects.get(id=self.kwargs['id'])
        comentarios = Comentarios.objects.filter(hotel=hotel)
        suma = comentarios.aggregate(Sum('puntuacion'))
        if comentarios.count() == 0:
            total_comentario = 1
        else:
            total_comentario = comentarios.count()
            
        if suma['puntuacion__sum'] is None:
            suma_puntuacion = 0
        else:
            suma_puntuacion = suma['puntuacion__sum']
        
        Hoteles.objects.filter(id=self.kwargs['id']).update(
            cant_votos=hotel.cant_votos+1,
            calificacion= suma_puntuacion / total_comentario
        )
        return reverse('app1:detalle_hotel', kwargs={"pk": self.kwargs['id']})

app1/templates/app1/comentar.html
{% extends 'base.html' %}

{% block titulo %} Registro {% endblock %}

{% block contenidos %}
<div class="container mt-5 text-center">
    <h1 class="mt-5">{{hotel.nombre}}</h1>
    <h5>direccion</h5>

    <form class="mt-5" method="POST" action="" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class="btn btn-success" value="Enviar">
    </form>
</div>
{% endblock %}

app1/templates/app1/detalle_hotel.html
{% extends 'base.html' %}

{% block titulo %} Detalle Hotel {% endblock %}

{% block contenidos %}
<div class="container mt-3">
    <div class="row mt-5">
        <div class="col-md-4">
            <img src="https://picsum.photos/seed/picsum/354/400" alt="lorem-picsum">
            <br>
            <br>
            {% if user.is_authenticated %}
            <div class="d-grid gap-2">
                <a type="button" class="button-radius btn btn-warning btn-lg" href="{% url 'app1:comentar' id=detalle_hotel.id %}"> Calificar </a>
            </div>
            {% else %}
            <div class="d-grid gap-2">
                Registrate para calificar a éste hotel! 
                <a type="button" class="button-radius btn btn-outline-success btn-lg"> Registrar </a>
            </div>

            {% endif %}
        </div>
        <div class="col-md-8 ps-4">
            <h1>{{detalle_hotel.nombre}}</h1>
            <h3 class="text-center" >{{detalle_hotel.calificacion}} | estrellas | {{detalle_hotel.cant_votos}}</h3>
            <p>{{detalle_hotel.descripcion}}</p>

            {% for atributo in atributos_hotel %}
                <p><strong>{{atributo.atributo}}:</strong> {{atributo.valor_atributo}}</p>
            {% endfor %}
        </div>

    </div>
    <br>
    <br>
    <div class="row">
        <h1>Comentarios</h1>
        {% for comentario in comentarios %}
        <div class="d-flex p-3 mt-3">
            <img src="https://cdn.pixabay.com/photo/2016/11/18/23/38/child-1837375_960_720.png" alt="John Doe"
                 class="flex-shrink-0 me-3 mt-3 rounded-circle" style="width:60px;height:60px;">
            <div>
                <small class="text-end"></small>
                <p class="text-end">{{comentario.puntuacion}} | {{comentario.fecha}}</p>
                <h6>{{comentario.nombre_usuario}}</h6>
                <p>{{comentario.comentario}}</p>
            </div>
        </div>
        {% endfor %}

    </div>

</div>
{% endblock %}

app1/templates/app1/index.html
{% extends 'base.html' %}

{% block titulo %} Hotel Advisor {% endblock %}

{% block contenidos %}
<div class="container-fluid mt-3">
    <div class="row p-2">
      
      <div class="col-md-2 col-lg-2">
        
        <div class="row">

          <div class="card">
            <h4 class="card-title"> Calificación</h4>
            <form method="POST" action="{% url 'app1:index' %}">
              {% csrf_token %}
              <input type="hidden" name="estrellas" id="estrellas" value=5>
              <input type="submit" value="5 Estrellas">
            </form>
            <form method="POST" action="{% url 'app1:index' %}">
              {% csrf_token %}
              <input type="hidden" name="estrellas" id="estrellas" value=4>
              <input type="submit" value="4 Estrellas">
            </form>
            <form method="POST" action="{% url 'app1:index' %}">
              {% csrf_token %}
              <input type="hidden" name="estrellas" id="estrellas" value=3>
              <input type="submit" value="3 Estrellas">
            </form>
            <form method="POST" action="{% url 'app1:index' %}">
              {% csrf_token %}
              <input type="hidden" name="estrellas" id="estrellas" value=2>
              <input type="submit" value="2 Estrellas">
            </form>
            <form method="POST" action="{% url 'app1:index' %}">
              {% csrf_token %}
              <input type="hidden" name="estrellas" id="estrellas" value=1>
              <input type="submit" value="1 Estrellas">
            </form>
            <form method="POST" action="{% url 'app1:index' %}">
              {% csrf_token %}
              <input type="hidden" name="estrellas" id="estrellas" value=0>
              <input type="submit" value="0 Estrellas">
            </form>
          </div>
          <div class="card mt-5">
            <h4 class="card-title"> Ordernar por</h4>
            <form method="POST" action="{% url 'app1:index' %}">
              {% csrf_token %}
              <input type="hidden" name="nombre" id="nombre" value='nombre'>
              <input type="submit" value="nombre">
            </form>
            <form method="POST" action="{% url 'app1:index' %}">
              {% csrf_token %}
              <input type="hidden" name="calificacion" id="calificacion" value='calificacion'>
              <input type="submit" value="Calificación">
            </form>
            <form method="POST" action="{% url 'app1:index' %}">
              {% csrf_token %}
              <input type="hidden" name="cant_votos" id="cant_votos" value='cant_votos'>
              <input type="submit" class="" value="Cant Votos">
            </form>
          </div>

        </div>
      </div>
      <div class=" col-md-10 col-lg-10">
        <div class="row">
            <div class="col-md-6 col-lg-6">
              {% for hotel in hoteles %}
              <div class="card card-hotel mb-3 mt-3">
                <div class="row">
                  <div class="col-md-4">
                    <img src="https://picsum.photos/seed/picsum/200/300" alt="lorem-picsum">
                  </div>
                  <div class="col-md-8">
                    <div class="card-body ps-4">
                      <h5 class="card-title">{{hotel.nombre}}</h5>
                      <p class="text-center">{{hotel.calificacion}}| estrellas | {{hotel.cant_votos}}</p>
                      
                      <small class="card-text">{{hotel.descripcion|truncatechars:150}}</small>
                      <br>
                      <br>
                      <small class="card-text">Dirección</small>
                      <p class="text-center"> <a href="{% url 'app1:detalle_hotel' pk=hotel.id %}">Ver Ficha</a> </p>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
            </div>
            <div class="col-md-6 col-lg-6">
              {% for comentario in comentarios %}
              <div class="d-flex p-3 mt-3">
                  <img src="https://cdn.pixabay.com/photo/2016/11/18/23/38/child-1837375_960_720.png" alt="John Doe"
                       class="flex-shrink-0 me-3 mt-3 rounded-circle" style="width:60px;height:60px;">
                  <div>
                      <small class="text-end"></small>
                      <p class="text-end">{{comentario.hotel.nombre|truncatechars:20 }} | {{comentario.puntuacion}} | {{comentario.nombre_usuario}} |{{comentario.fecha}}</p>
                      <h6>{{comentario.nombre_usuario}}</h6>
                      <p>{{comentario.comentario}}</p>
                  </div>
              </div>
              {% endfor %}
            </div>
        
        </div>
      </div>
    </div>

  </div>





{% endblock %}

app1/templates/app1/registro.html
{% extends 'base.html' %}

{% block titulo %} Registro {% endblock %}

{% block contenidos %}
    <div class="row justify-content-center">
        <div class="col-md-4 p-3" style="background-color: whitesmoke;">
            <form method="post" action="" novalidate>
                {% csrf_token %}
                {{form.as_p}}
                <br>
                <div class="d-grid gap-2 form-group">
                    <input class="btn btn-success" type="submit" value="Registrar">
                </div>
            </form>
        </div>
        
    </div>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="es">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Poiret+One" rel="stylesheet" type="text/css">
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <title>{% block titulo %} {% endblock %}</title>
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
          <a class="navbar-brand" href="{% url 'app1:index' %}">
            <img src="{% static 'img/red_hotel.svg' %}" alt="" width="30" height="24" class="d-inline-block align-text-top">
            Hotel Advisor
          </a>
          <form class="d-flex" method="POST" action="{% url 'app1:index' %}">
            {% csrf_token %}
            <input class="form-control me-2" name="search" type="search" placeholder="Buscar" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Buscar</button>
          </form>
          
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            {% if user.is_authenticated %}
            <span class="navbar-text">
              Bienvenido {{user.username}} !
            </span>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'logout' %}?next={% url 'app1:index' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Entrar</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'app1:registro' %}">Registrar</a>
            </li>

            {% endif %}
          </ul>
          
          
        </div>
      </div>
    </nav>
  </header>

  {% block login %} {% endblock %}
  {% block contenidos %} {% endblock %}
 





  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8"
    crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js" integrity="sha384-lpyLfhYuitXl2zRZ5Bn2fqnhNAKOAaM/0Kr9laMspuaMiZfGmfwRNFh8HlMy49eQ" crossorigin="anonymous"></script>
    -->
</body>

</html>